### ISSUE TITLE
Lazy load by hotkeys doesn't execute the associated action the first time (when loading)

### ISSUE THREAD

**Issue by alem0lars** [Shougo/dein.vim#78] opened 2016-04-16 08:07 UTC
# Problems summary

When I lazily load a plugin using a hotkey, the first time I use the hotkey the action isn't executed.

For example: `,cs` loads the plugin `vim-surround` but if I type `,cs'"` the single quotes aren't replaced with the double quotes. Typing that hotkey another time (when the plugin is already loaded) the action will be executed.

## Expected

The action should be executed even for the first time I type the hotkey.

## Environment Information

 * OS: GNU/Linux (distro: Gentoo)
 
* Vim version:

```
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -g -Wno-error -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/var/tmp/portage/app-editors/neovim-0.1.2/work/neovim-0.1.2_build/config -I/var/tmp/portage/app-editors/neovim-0.1.2/work/neovim-0.1.2/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.1.2/work/neovim-0.1.2_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.1.2/work/neovim-0.1.2_build/include
Compiled by portage@kate

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if has('vim_starting')
  execute ' set runtimepath^=' . substitute(
          \ fnamemodify('/path/to/dein/dir', ':p') , '/$', '', '')
endif

call dein#begin(expand('~/.cache/dein'))
call dein#add('tpope/vim-repeat', {
      \ 'lazy': 1,
      \ 'on_map': '.'})
call dein#add('tpope/vim-surround', {
      \ 'lazy': 1,
      \ 'depends': ['vim-repeat'],
      \ 'on_map': ',cs'})
call dein#end()
call dein#save_state()

if dein#check_install()
  call dein#install()
endif

syntax enable
filetype plugin indent on
```

## The reproduce ways from Vim starting (Required!)

 1. Start Vim
 2. Type `,cs'"` for the first time: the plugin will be loaded but the action isn't executed
 3. Type `,cs'"` another time: the action will be executed (the plugin is already loaded by step (2))

**Comment by Shougo** [comment] 2016-04-17 05:35
```vim
call dein#add('tpope/vim-surround', {
      \ 'lazy': 1,
      \ 'depends': ['vim-repeat'],
      \ 'on_map': ',cs'})
```

The mappings is wrong.

```
call dein#add('tpope/vim-surround', {
      \ 'lazy': 1,
      \ 'depends': ['vim-repeat'],
      \ 'on_map': 'cs'})
```

This is correct.
https://github.com/tpope/vim-surround/blob/master/plugin/surround.vim#L580

**Comment by Shougo** [comment] 2016-04-17 05:38
Cannot reproduce it in the fixed .vimrc.
Closing.

**Closed by Shougo** 2016-04-17 05:38 UTC
Labels: cannot reproduce

**Comment by alem0lars** [comment] 2016-04-17 06:23
Thanks good catch :)

I'm having a similar issue with tcomment plugin (I've double checked the docs this time):

```viml
call dein#add('tomtom/tcomment_vim', {
      \ 'lazy': 1,
      \ 'on_map': ['gc', 'g<', 'g>', '<C-_>', '<Leader>_'],
      \ })
```

It works with the first 3 hotkeys, but with the hotkeys starting with `<C-_>` and `<Leader>_` it doesn't work and there is the described problem.

Here is the docs relative to the mappings:
[https://github.com/tomtom/tcomment_vim/blob/master/doc/tcomment.txt#L240](https://github.com/tomtom/tcomment_vim/blob/master/doc/tcomment.txt#L240)

**Comment by Shougo** [comment] 2016-04-17 06:28
@alem0lars I don't use tcomment_vim.
Please upload the reproduce ways.

**Comment by Shougo** [comment] 2016-04-17 06:33
For `<Leader>_`, `\_s` works.
For `<C-_>`, `<C-_>s` works.
But the input timing is hard.
It is the feature.

**Comment by alem0lars** [comment] 2016-04-17 06:38
Not for me: I type `<C-_>s` and it does the same as if I typed `s`,i.e. goes in insert mode and substitute the next character.
If I try again (the second time), it works.

The same for `<Leader>_`.

Does the hotkeys work **the first time** you type them (after opening the editor)?

**Comment by alem0lars** [comment] 2016-04-17 06:39
## The reproduce ways from Vim starting

1. Start Vim
2. Type some text.
3. Type `<Leader>__` (or `<Leader>_s`): it doesn't do the right action
4. Type `<Leader>__` (or `<Leader>_s`) again (the second time): it works, it does the right action.

**Comment by Shougo** [comment] 2016-04-17 06:41
> Does the hotkeys work the first time you type them (after opening the editor)?

It works, but the timing is hard.
You should not use the prefix keys like this.

```vim
call dein#add('tomtom/tcomment_vim', {
      \ 'lazy': 1,
      \ 'on_map': ['gc', 'g<', 'g>', '<C-_>s', '<Leader>_s', ...],
      \ })
```

**Comment by Shougo** [comment] 2016-04-17 06:45
I have fixed `<C-_>_` error.
And `<Leader>__` works.

**Comment by alem0lars** [comment] 2016-04-17 06:50
Are you suggesting me to use the complete hotkeys (and not just the prefixes)?

**Comment by Shougo** [comment] 2016-04-17 06:56
@alem0lars Yes. Or to increase 'timeoutlen'.

**Comment by alem0lars** [comment] 2016-04-17 07:06
But it should still work (without complete hotkeys), right?

Because some plugins define a lot of hotkeys (e.g. > 20) so it's difficult to maintain them

**Comment by Shougo** [comment] 2016-04-17 07:07
@alem0lars It works for me, but sometimes fails.
And "on_map" does not support all plugins.

**Comment by alem0lars** [comment] 2016-04-17 07:35
What do you mean with:

> And "on_map" does not support all plugins.

?

**Comment by Shougo** [comment] 2016-04-17 07:38
> And "on_map" does not support all plugins.
 
The lazy feature is the trick.  So you cannot specify to lazy all plugins.

**Comment by alem0lars** [comment] 2016-04-17 07:39
Which kind of plugins can't be made lazy?

**Comment by Shougo** [comment] 2016-04-17 07:40
I don't know the example.
But some plugins are hard like tcommenter.

**Comment by alem0lars** [comment] 2016-04-17 07:42
Ok thanks :)

Can I also specify something like `<Plug>Dsurround` in `on_map`?

**Comment by Shougo** [comment] 2016-04-17 07:43
You can use `<Plug>Dsurround`.
But you must map `<Plug>Dsurround` to some keys.

**Comment by wsdjeg** [comment] 2016-04-17 11:54
@alem0lars here is a lot of lazy load plugin examples work with dein.
