### ISSUE TITLE
call dein#recache_runtimepath() when removing a plugin

### ISSUE THREAD

**Issue by nhooyr** [Shougo/dein.vim#174] opened 2017-01-03 12:05 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When removing a plugin from my `dein.toml` file, dein does not call `dein#recache_runtimepath()` and thus I can still see the help file from removed plugins, though I cannot actually use the plugin.

## Expected
It should call `dein#recache_runtimepath()` like it does when I add a plugin.

## Environment Information
 * OS: macOS 10.12.2
 * Nvim version: 0.1.7

## Steps
https://asciinema.org/a/21ls02g64b3acctlce5zph7xp

If you do not understand based on the video, I will create a minimal vimrc and reproduction steps.

**Comment by Shougo** [comment] 2017-01-03 13:35
Please create the minimal init.vim like this.
https://github.com/Shougo/dein.vim/issues/166

**Comment by nhooyr** [comment] 2017-01-03 13:53
Ah, it is because of lazy loading.

```vim
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('Shougo/echodoc.vim', {'on_event': 'CompleteDone'})
call dein#end()
```

1. Launch neovim and `:call dein#update()`
2. `:h echodoc` works and so does `:call echodoc#enable()`
3. Remove the add line from init.vim
4. start neovim again and notice that `:h echodoc` still works but `:call echodoc#enable()` does not.

**Comment by Shougo** [comment] 2017-01-03 14:05
I will test it.

**Comment by Shougo** [comment] 2017-01-03 14:41
I cannot reproduce it.

**Comment by nhooyr** [comment] 2017-01-03 14:45
@Shougo I can still reproduce.

Here is another video using the above init.vim https://asciinema.org/a/cwtahgeeil3d5u75u330hnwu8

**Comment by Shougo** [comment] 2017-01-03 14:48
Why I cannot reproduce the problem with the vimrc?

**Comment by nhooyr** [comment] 2017-01-03 14:48
I have no idea, can you record you trying with asciinema?

**Comment by Shougo** [comment] 2017-01-03 14:50
I need the other testers.

**Comment by Shougo** [comment] 2017-01-03 15:01
> I have no idea, can you record you trying with asciinema?

https://asciinema.org/a/1dyebje77vcqoiph4dyyv7ins

**Comment by nhooyr** [comment] 2017-01-03 15:04
@Shougo you used the wrong init.vim. You don't have `, {'on_event': 'CompleteDone'}`. that is needed for the bug to be reproduced.

**Comment by Shougo** [comment] 2017-01-03 15:07
OK, I get it.
It is the bug.

**Comment by Shougo** [comment] 2017-01-03 15:12
Fixed in vimproc branch.

**Closed by Shougo** 2017-01-03 15:12 UTC
Labels: bug
