### ISSUE TITLE
Equivalent of vim-plug do post-install step for fruzzy

### ISSUE THREAD

**Issue by gotgenes** [Shougo/dein.vim#374] opened 2020-07-12 05:24 UTC
I'm trying to understand with dein how to do the equivalent of vim-plug's `do` for installing [fruzzy](https://github.com/raghur/fruzzy) with the native module. In the [installation instructions](https://github.com/raghur/fruzzy#installation), for vim-plug, the user should put the following 

```
Plug 'raghur/fruzzy', {'do': { -> fruzzy#install()}}
```

I feel like there must be an equivalent using dein's hooks, but I haven't figured it out. I first tried

```
call dein#add('raghur/fruzzy', {'hook_post_update': fruzzy#install})
```

this led to the error

```
E121: Undefined variable: fruzzy#install                                                                                
E116: Invalid arguments for function dein#add  
```

I then tried
```
call dein#add('raghur/fruzzy', {'hook_post_update': 'fruzzy#install'})
```
but this resulted in the error
```
[dein] Error occurred while executing hook: fruzzy
[dein] Vim:E492: Not an editor command: fruzzy#install
```

I also tried
```
call dein#add('raghur/fruzzy', {'hook_post_update': 'fruzzy#install()'})
```
which resulted in the error
```
[dein] Error occurred while executing hook: fruzzy
[dein] Vim:E492: Not an editor command: fruzzy#install()
```

I then tried
```
call dein#add('raghur/fruzzy', {'hook_post_update': 'call fruzzy#install()'})
```
which led to the error
```
[dein] Error occurred while executing hook: fruzzy                                                                      
[dein] Vim(call):E117: Unknown function: fruzzy#install  
```

All of these were using a fresh cache — removing `call dein#add('raghur/fruzzy', …)` from the `init.vim`, quitting, starting Neovim, calling `call dein#recache_runtimepath()`, adding back the next attempt of `call dein#add(…`, quitting Neovim, and starting Neovim again.

Maybe I'm using the wrong hook, or maybe I'm using the hook incorrectly. I'm trying hard to understand dein better. I appreciate any help.

**Comment by gotgenes** [comment] 2020-07-12 06:31
I found [this comment](https://github.com/raghur/fruzzy/issues/11#issuecomment-431576748) in raghur/fruzzy#11, and a reply from @Shougo which indicates `hook_post_update` is the intended hook to be used, and the last form of

```
call dein#add('raghur/fruzzy', {'hook_post_update': 'call fruzzy#install()'})
```

is intended to work, but it does not, for a completely new cache.

**Comment by Shougo** [comment] 2020-07-12 08:52
It works for me.
And you don't understand that `is intended to work, but it does not, for a completely new cache.`

You need to explain it more clearly with reproduce instruction.

I will close it.

Note: To work `hook_post_update`, fruzzy must be installed or updated.

>All of these were using a fresh cache — removing call dein#add('raghur/fruzzy', …) from the init.vim, quitting, starting Neovim, calling call dein#recache_runtimepath(), adding back the next attempt of call dein#add(…, quitting Neovim, and starting Neovim again.

I don't understand.

**Comment by Shougo** [comment] 2020-07-12 08:53
> Maybe I'm using the wrong hook, or maybe I'm using the hook incorrectly. I'm trying hard to understand dein better. I appreciate any help.

Yes.  You seems dein's usage is wrong.  But you don't upload the minimal vimrc.
We have not ESP skills.  Please read other issues.

**Closed by Shougo** 2020-07-12 08:52 UTC

**Comment by Shougo** [comment] 2020-07-12 08:55
> call dein#add('raghur/fruzzy', {'hook_post_update': 'call fruzzy#install()'})

It should work.  If it does not work, it may be bug.  But your description is not understand-able.

**Comment by Shougo** [comment] 2020-07-12 08:59
Please compare the issue and your issue.
https://github.com/Shougo/dein.vim/issues/373

Which issue better to understand??

**Comment by gotgenes** [comment] 2020-07-12 21:31
Now that I know this is a bug in dein, I have filed #375.

Thanks.
