### ISSUE TITLE
Error detected while processing fuction ... install#_rm

### ISSUE THREAD

**Issue by gravndal** [Shougo/dein.vim#107] opened 2016-05-23 15:13 UTC
# Problems summary

Invalid arguments passed to delete calls in `dein#install#_rm()` when regenerating dein cache, resulting in `dein#end()` failing.
## Expected

The dein cache being regenerated successfully, and the call to `dein#end()` succeeding.
## Environment Information
- OS: Arch
- Vim version: nvim 0.1.4
## Provide a minimal .vimrc with less than 50 lines (Required!)

``` vim
" Your minimal .vimrc
set shell=bash
set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.cache/dein'))
call dein#add('Shougo/dein.vim')
call dein#add('lervag/vimtex')
call dein#end()
```
## The reproduce ways from Vim starting (Required!)
1. Open vim and call `dein#install()`
2. Restart vim and comment `call dein#add('lervag/vimtex')`
3. Restart vim and uncomment `" call dein#add('lervag/vimtex')`
4. Restart vim, get error in `dein#end()`
## Screen shot (if possible)

![2016-05-23-16 17 04](https://cloud.githubusercontent.com/assets/4656860/15474864/13525a8a-2107-11e6-9621-1d6083316744.png)
## Upload the log messages by `:redir` and `:message`

```
Error detected while processing function dein#end[1]..dein#util#_end[39]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[7]..<SNR>8_clear_runtimepath[25]..dein#install#_rm:
line    6:
E16: Invalid range
E16: Invalid range
"init.vim" 6L, 201C
```

**Comment by Shougo** [comment] 2016-05-26 01:30
I cannot reproduce the problem in neovim-0.15-dev.
Please use the latest neovim.
I think neovim-0.14 has the bug.

You can check it by `call delete({directory_path}, 'rf')`.

**Comment by gravndal** [comment] 2016-05-26 02:05
Tested just now, and simply calling delete on a copy of the vimtex repository from both vim 7.4.1794 and neovim-0.1.5-dev (built just now) yields the same results. So this looks like a bug in vim.

**Comment by Shougo** [comment] 2016-05-26 02:39
OK.  I get it.
It should be fixed.

**Comment by Shougo** [comment] 2016-05-27 02:27
@gravndal Please try https://github.com/vim/vim/issues/700.

**Comment by gravndal** [comment] 2016-05-27 17:38
Tried it, and it does fix this. I do not have a windows machine, so I can't look into the issues they appear to be having.

**Comment by Shougo** [comment] 2016-05-27 17:54
You should not use `[]` in the filename.

**Comment by Shougo** [comment] 2016-06-18 00:55
I have ported it.  Please test.

https://github.com/neovim/neovim/pull/4936

**Comment by Shougo** [comment] 2017-04-20 09:46
I will add `if_python3` remove feature.

**Closed** 2017-04-23 09:08 UTC
Labels: cannot fix
