### ISSUE TITLE
LSP misbehave when using dein-option "on_ft"

### ISSUE THREAD

**Issue by pwnr3** [Shougo/dein.vim#428] opened 2021-09-12 12:16 UTC
# Problem
dein config for lspconfig(in a toml file)
```
# in init.vim
call dein#load_toml(s:mod_toml, { 'lazy': 1 })

# in mod.toml
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'VimEnter'
on_ft = [ 'typescript', 'javascript' ]
hook_source = 'lua require("plugins.lspconfig")'
```
* when enable on_event and on_ft, **misbehave**
* when enable on_event only, **no problem**
* when enable on_ft only, **misbehave**
* In all situations above, I can use lsp related commands such as "LspInfo", "LspStart"...

***misbehave*** -> lsp can detect syntax problem only when I enter vim, after that, no matter how I edit the code,
error mark doesn't occur when I make some wrong code, error doesn't disappear when I fix the wrong code part

I want to load lspconfig only when I edit javascript/typescript file, so I try **on_ft** keyword.

# Clue
After some test, I think the key point maybe the file load order, you can check that in the following two logs with command
`:scriptnames`.
You can notice that there are two orders for **lspconfig** and **runtime/\*/javascript.vim**
PS: I am not so good at vim or dein internal logic, I can only guess based on these limited information.

```
no problem
  27: /opt/local/share/nvim/runtime/syntax/syntax.vim
 28: /opt/local/share/nvim/runtime/syntax/synload.vim
 29: /opt/local/share/nvim/runtime/syntax/syncolor.vim
 30: /opt/local/share/nvim/runtime/ftplugin/javascript.vim
 31: /opt/local/share/nvim/runtime/indent/javascript.vim
 32: /opt/local/share/nvim/runtime/syntax/javascript.vim
 33: /opt/local/share/nvim/runtime/plugin/gzip.vim
 34: /opt/local/share/nvim/runtime/plugin/health.vim
 35: /opt/local/share/nvim/runtime/plugin/man.vim
 36: /opt/local/share/nvim/runtime/plugin/matchit.vim
 37: /opt/local/share/nvim/runtime/plugin/matchparen.vim
 38: /opt/local/share/nvim/runtime/plugin/netrwPlugin.vim
 39: /opt/local/share/nvim/runtime/plugin/rplugin.vim
 40: /opt/local/share/nvim/runtime/plugin/shada.vim
 41: /opt/local/share/nvim/runtime/plugin/spellfile.vim
 42: /opt/local/share/nvim/runtime/plugin/tarPlugin.vim
 43: /opt/local/share/nvim/runtime/plugin/tohtml.vim
 44: /opt/local/share/nvim/runtime/plugin/tutor.vim
 45: /opt/local/share/nvim/runtime/plugin/zipPlugin.vim
 46: ~/.config/nvim/cache/dein/repos/github.com/nvim-treesitter/nvim-treesitter/plugin/nvim-treesitter.vim
 47: ~/.config/nvim/cache/dein/repos/github.com/nvim-treesitter/nvim-treesitter-textobjects/plugin/nvim-treesitter-textobjects.vim
 48: ~/.config/nvim/cache/dein/repos/github.com/neovim/nvim-lspconfig/plugin/lspconfig.vim
 49: ~/.config/nvim/cache/dein/repos/github.com/hrsh7th/nvim-cmp/plugin/cmp.lua
 50: ~/.config/nvim/cache/dein/repos/github.com/hrsh7th/vim-vsnip/plugin/vsnip.vim
```
```
misbehave
  27: /opt/local/share/nvim/runtime/syntax/syntax.vim
 28: /opt/local/share/nvim/runtime/syntax/synload.vim
 29: /opt/local/share/nvim/runtime/syntax/syncolor.vim
 30: ~/.config/nvim/cache/dein/repos/github.com/neovim/nvim-lspconfig/plugin/lspconfig.vim
 31: ~/.config/nvim/cache/dein/repos/github.com/hrsh7th/nvim-cmp/plugin/cmp.lua
 32: ~/.config/nvim/cache/dein/repos/github.com/hrsh7th/vim-vsnip/plugin/vsnip.vim
 33: ~/.config/nvim/cache/dein/repos/github.com/hrsh7th/cmp-buffer/after/plugin/cmp_buffer.lua
 34: /opt/local/share/nvim/runtime/ftplugin/javascript.vim
 35: /opt/local/share/nvim/runtime/indent/javascript.vim
 36: /opt/local/share/nvim/runtime/syntax/javascript.vim
 37: /opt/local/share/nvim/runtime/plugin/gzip.vim
 38: /opt/local/share/nvim/runtime/plugin/health.vim
 39: /opt/local/share/nvim/runtime/plugin/man.vim
 40: /opt/local/share/nvim/runtime/plugin/matchit.vim
 41: /opt/local/share/nvim/runtime/plugin/matchparen.vim
 42: /opt/local/share/nvim/runtime/plugin/netrwPlugin.vim
 43: /opt/local/share/nvim/runtime/plugin/rplugin.vim
 44: /opt/local/share/nvim/runtime/plugin/shada.vim
 45: /opt/local/share/nvim/runtime/plugin/spellfile.vim
 46: /opt/local/share/nvim/runtime/plugin/tarPlugin.vim
 47: /opt/local/share/nvim/runtime/plugin/tohtml.vim
 48: /opt/local/share/nvim/runtime/plugin/tutor.vim
 49: /opt/local/share/nvim/runtime/plugin/zipPlugin.vim
 50: ~/.config/nvim/cache/dein/repos/github.com/nvim-treesitter/nvim-treesitter/plugin/nvim-treesitter.vim
 51: ~/.config/nvim/cache/dein/repos/github.com/nvim-treesitter/nvim-treesitter-textobjects/plugin/nvim-treesitter-textobjects.vim
```

# Platform
MacOS 10.13.6

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3

with latest dein version

**Comment by Shougo** [comment] 2021-09-12 13:49
The lazy loading is not magic solution.  I may not fix it.

But I need to reproduce the problem.

Why you have ignored the issue template?  I need the minimal vimrc and the reproduce instruction.

The minimal vimrc is not means minimal cut from your config.  It can be executed by anyone.

**Comment by Shougo** [comment] 2021-09-12 13:57
It seems `BufEnter` autocmd call is needed.

**Comment by pwnr3** [comment] 2021-09-12 13:58
config for dein `https://github.com/pwnr3/dots/blob/master/nvim/config/dein.vim#L45`
config for plugin setup `https://github.com/pwnr3/dots/blob/master/nvim/config/lazy-mods.toml#L91`

**Comment by Shougo** [comment] 2021-09-12 14:00
Please test the latest version.

**Comment by pwnr3** [comment] 2021-09-12 14:15
test on version latest `ffe2030c`, problem still there

**Comment by Shougo** [comment] 2021-09-12 14:27
Really?  Please create the minimal vimrc and the reproduce instructions.
It does not mean upload your config.

**Comment by Shougo** [comment] 2021-09-12 14:28
Please compare with the issue.
https://github.com/Shougo/dein.vim/issues/427

If you don't upload them, I will close it.

**Comment by pwnr3** [comment] 2021-09-12 14:35
Sorry for late response, I am trying to give a reproduce instructions.

**Comment by pwnr3** [comment] 2021-09-12 14:41
```
set runtimepath^=~/.config/nvim/dein/repos/github.com/Shougo/dein.vim/
if dein#load_state('~/.config/nvim/dein')
  call dein#begin('~/.config/nvim/dein')
  call dein#add('neovim/nvim-lspconfig', {'lazy': 1, 'on_ft': 'typescript', 'hook_source': 'lua require"lspconfig".tsserver.setup{}'})
  "call dein#add('neovim/nvim-lspconfig', {'lazy': 1, 'on_event': 'VimEnter', 'hook_source': 'lua require"lspconfig".tsserver.setup{}'})
  call dein#end()
  call dein#save_state()
endif
set laststatus=2
```

steps
1. use **on_ft** config
2. edit a simple typescript file "test.ts"
```typescript
function main(): foo {}
```
3. you will find that lsp doesn't work.
    save and close, reopen it, you can find that lsp marks the error.
    fix the error, error mark is still there
4. but if you use "on_evet" config, lsp works

**Comment by Shougo** [comment] 2021-09-12 14:42
OK.  I will test it.

**Comment by Shougo** [comment] 2021-09-12 15:14
```vim
call dein#add('neovim/nvim-lspconfig', {'lazy': 1, 'on_ft': 'typescript', 'hook_source': 'lua require"lspconfig".tsserver.setup{}'})
```

It works for me.  Closing.

**Comment by Shougo** [comment] 2021-09-12 15:15
Please upload the real reproduce-able instructions.

**Comment by Shougo** [comment] 2021-09-12 15:18
I get it.  It seems loading order problems.

**Comment by pwnr3** [comment] 2021-09-12 15:21
Why it works for you but fails on me?
I test on MacOS, I upgrade to neovim-devel 0.6(installed by mac port) and the problem is still there.

**Comment by Shougo** [comment] 2021-09-12 15:22
https://github.com/pwnr3/dots/blob/master/nvim/config/dein.vim#L46

You must execute `filetype plugin indent on` after `dein#end()`.

**Comment by Shougo** [comment] 2021-09-12 15:23
I think you have not read dein's examples.

**Comment by Shougo** [comment] 2021-09-12 15:24
> Why it works for you but fails on me?

Yes.  It is failed for me.  And I get the reason.

**Closed by Shougo** 2021-09-12 15:23 UTC
Labels: invalid

**Comment by Shougo** [comment] 2021-09-12 15:25
It fixes your problem.

```vim
set nocompatible
set rtp+=~/work/dein.vim/

call dein#begin('~/.cache/test')

call dein#add('neovim/nvim-lspconfig', {'lazy': 1, 'on_ft': 'typescript', 'hook_source': 'lua require"lspconfig".tsserver.setup{}'})
"call dein#add('neovim/nvim-lspconfig', {'lazy': 1, 'on_event': 'VimEnter', 'hook_source': 'lua require"lspconfig".tsserver.setup{}'})

call dein#end()

filetype plugin indent on
```

**Comment by pwnr3** [comment] 2021-09-12 15:28
Yes, I add that and it works, thanks!
Sorry for my mistake while creating this issue, I ignore the important part of the issue template and make reproduce hard.

**Comment by Shougo** [comment] 2021-09-12 15:47
The report must be reproduced by anyone without ESP skills.
The issue template is very important.

Your issue cannot reproduced and fixed without the minimal vimrc (and instructions).
I think it is good experience.
