### ISSUE TITLE
whenever I change my dein#add list, gvim will spend more time on the next start

### ISSUE THREAD

**Issue by fcying** [Shougo/dein.vim#210] opened 2017-05-02 13:43 UTC
gvim 8.0-587
os: win10

most time spend in the flowing script
```
057.000  000.000  000.000: sourcing D:\tool\vim\bundle\repos\github.com\Shougo\dein.vim\autoload\dein\job.vim
3473.000  000.000  000.000: sourcing D:\tool\vim\bundle\.cache\_vimrc\.dein\autoload\dein\types\raw.vim
7393.000  000.000  000.000: sourcing D:\tool\vim\bundle\.cache\_vimrc\.dein\ftdetect\ftdetect.vim
```

my dein config
```
exec 'set runtimepath+=' . fnameescape(s:dein_dir)
if dein#load_state(g:plugin_dir)
    call dein#begin(g:plugin_dir)
    call dein#add('Shougo/dein.vim')
    ...
    ...
    call dein#end()
    call dein#call_hook('source')
    call dein#save_state()
endif
```

The attachment is the first start and the second start contrast

[startuptime.txt](https://github.com/Shougo/dein.vim/files/970630/startuptime.txt)

**Comment by Shougo** [comment] 2017-05-03 04:16
Your reproduce way is invalid.
I have not ESP skills.
Please read other issues.

**Comment by Shougo** [comment] 2017-05-03 04:18
I think this is feature.
Because, if you change the dein#add() list, dein.vim re-generate the cache by `dein#recache_runtimepath()`.
It is slow especially in Windows.

**Comment by Shougo** [comment] 2017-05-03 04:18
You can disable the behavior by disabling merged feature.
Please see the documentation.

**Closed by Shougo** 2017-05-03 04:18 UTC
Labels: cannot reproduce, reproduce ways
