### ISSUE TITLE
E121: Undefined variable: g:dein#install_process_timeout

### ISSUE THREAD

**Issue by drodger** [Shougo/dein.vim#41] opened 2016-03-16 02:17 UTC
# Problems summary
Problem started with this commit:
https://github.com/Shougo/dein.vim/commit/0714f931aa6612b13a63dbd9c7179788e27f0edb

Error:
```
Error detected while processing function dein#add[1]..dein#parse#_add[1]..dein#parse#_dict:
line    1:
E121: Undefined variable: g:dein#install_process_timeout
E15: Invalid expression: { 'type': 'none', 'uri': '', 'rev': '', 'rtp': '', 'if': 1, 'sourced': 0, 'local': 0, 'base': dein#util#_get_base_path() . '/repos', 'frozen': 0, 'depends': [], 'timeout': g:dein#install_process_timeout, 'dummy_commands': [], 'dummy_mappings': [], 'build': {}, 'on_i': 0, 'on_ft': [], 'on_cmd': [], 'on_func': [], 'on_map': [], 'on_path': [], 'on_source': [], 'pre_cmd': [], 'pre_func': [], }
```

## Environment Information
 * OS: Ubuntu Linux 15.04
 * Vim version:  neovim-0.1.2ubuntu1+git201603131848+2368+17~ubuntu15.04.1

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=$HOME/.config/nvim/repos/github.com/Shougo/dein.vim

call dein#begin(expand('~/.cache/dein'))
call dein#add('Shougo/dein.vim')
call dein#end()
```

## The reproduce ways from Vim starting (Required!)
Occurs on starting nvim

**Comment by Shougo** [comment] 2016-03-16 23:00
I cannot reproduce it.
Your dein.vim is too old.  Closing.

**Closed by Shougo** 2016-03-16 23:00 UTC

**Comment by drodger** [comment] 2016-03-16 23:19
I'm on the latest code. I tried removing ~/.cache/dein and re-ran dein#install(), it's working now. Thanks.
