### ISSUE TITLE
When use 'lazy' option get waring message 'plugin name is already defined.'

### ISSUE THREAD

**Issue by hare001** [Shougo/dein.vim#397] opened 2021-01-24 10:41 UTC
# Problems summary
When I use `call dein#add('suan/vim-instant-markdown', {'lazy': 1, 'on_ft': 'markdown'})` or `call dein#config('vim-instant-markdown', {'lazy': 1, 'on_ft': 'markdown'})`, I got a warning message when I save init.vim file.like this:`[dein] Plugin name "vim-instant-markdown" is already defined.`

## Expected
no warning message when I save init.vim file.

## Environment Information (Required!)

 * dein.vim version(SHA1):c6ddf04183606413870a0f8a86f61f8d58f85982

 * OS:macOS Catalina version 10.15.7

 * Vim/neovim version:NVIM v0.5.0-nightly

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
let s:dein_path = '~/.config/nvim/dein'
let &runtimepath = &runtimepath.','.s:dein_path.'/repos/github.com/Shougo/dein.vim'
call dein#begin(s:dein_path)
call dein#add('suan/vim-instant-markdown', {'lazy': 1, 'on_ft': 'markdown'})
"call dein#add('suan/vim-instant-markdown')
"call dein#config('vim-instant-markdown', {
			"\ 'lazy': 1, 'on_ft': 'markdown',
			"\ })
call dein#end()

if dein#check_install()
    call dein#install()
endif
autocmd! BufNewFile $MYVIMRC source %
```

## The reproduce ways from Vim starting (Required!)

 1. `:call dein#install()` to install plugins
 2. `:w` to save the init.vim file
 3. if the second step doesn't show warning message, use `:w` to save twice

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/1713345/105627690-46fa7080-5e73-11eb-8ff5-c0285ac39004.png)

## Upload the log messages by `:redir` and `:message` (if errored)
```
"init.vim" 483L, 11854C 已写入
[dein] Plugin name "vim-instant-markdown" is already defined.
[dein] Plugin name "vim-markdown-toc" is already defined.
```

**Comment by Shougo** [comment] 2021-01-24 10:48
Closing.  Because you don't have uploaded reproduce-able vimrc.

Why?  It is not included `BufWritePost` autocmd in the vimrc.

**Comment by Shougo** [comment] 2021-01-24 10:53
```vim
set runtimepath^=~/work/dein.vim
if dein#load_state('~/work/test')
  call dein#begin('~/work/test')

  " markdown
  call dein#add('suan/vim-instant-markdown')
  "call dein#config('vim-instant-markdown', {
        "\ 'lazy': 1, 'on_ft': 'markdown',
        "\ })
  call dein#add('mzlogin/vim-markdown-toc')
  "call dein#config('vim-markdown-toc', {
        "\ 'lazy': 1, 'on_ft': 'markdown',
        "\ })

  call dein#end()
  call dein#save_state()
endif

autocmd! bufwritepost $MYVIMRC source %
```

It works for me.

**Comment by Shougo** [comment] 2021-01-24 11:00
Reproduced.

**Closed** 2021-01-24 11:00 UTC
