### ISSUE TITLE
Lazy Load Vim-Devicons Not Working

### ISSUE THREAD

**Issue by weilbith** [Shougo/dein.vim#296] opened 2018-06-10 18:03 UTC
# Problems summary
I can't get [vim-devicons](https://github.com/ryanoasis/vim-devicons) to be lazy loaded.
I defined it as depending on a different plugin (`on_source`), sourced on an event (`on_event`), define it additionally as lazy. I uninstalled it and let it reinstall, recached the runtime path, but each time I start _Vim_ new, it is already sourced, also if the depending event/.. hasn't happened. As this plugin contains not only an `autoload` folder, but also a `plugin` directory, I don't get this.

## Expected
_Vim-Devicons_ can get lazy loaded as every other plugin also.

## Environment Information
 * dein.vim version(SHA1): 03411970ee364aee4e177819d384fcedcd88c743
 * OS: Ubuntu 16.4
 * Vim/neovim version: NVIM v0.2.2

## Provide a minimal .vimrc with less than 50 lines (Required!)
```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/dein.nvim/
call dein#begin(path)
call dein#add('ryanoasis/vim-devicons', {
      \ 'lazy': 1,
      \ 'on_event': 'InsertEnter'
      \ })
call dein#end()
```

## The reproduce ways from Vim starting (Required!)

 1. Start _Vim_ with this configuration and let the plugin get installed. Afterwards the plugin get loaded.
 2. Restart _Vim_ and don't enter insert mode. Execute `:echo dein#is_sourced('vim-devicons')` which results into `0`.

**Comment by Shougo** [comment] 2018-06-10 23:39
I don't understand it.

> Restart Vim and don't enter insert mode. Execute :echo dein#is_sourced('vim-devicons') which results into 0.

It is my intended behavior.
What is your problem?

If you don't explain it, I will close the issue.

**Comment by Shougo** [comment] 2018-06-10 23:41
> I defined it as depending on a different plugin (on_source), sourced on an event (on_event), define it additionally as lazy. I uninstalled it and let it reinstall, recached the runtime path, but each time I start Vim new, it is already sourced, also if the depending event/.. hasn't happened. As this plugin contains not only an autoload folder, but also a plugin directory, I don't get this.

It is not included in your minimal vimrcs and reproduce ways.
Why?

**Comment by Shougo** [comment] 2018-06-10 23:41
You should read this.

https://github.com/Shougo/dein.vim/issues/287

**Comment by Shougo** [comment] 2018-06-10 23:43
> Start Vim with this configuration and let the plugin get installed. Afterwards the plugin get loaded.

It is feature.  After the installation, the plugin is loaded.

**Comment by weilbith** [comment] 2018-06-11 05:05
> It is feature. After the installation, the plugin is loaded
That was just a statement not an report. 

>It is my intended behavior. What is your problem?
The point is that the plugin is defined to be loaded by the `InsertEnter` event, that's why. Means until the insert mode hasn't entered, `echo dein#is_sourced('vim-devicons')` should return `0`. And thats what it doesn't. It's always loaded from the early beginning. Don't matter to what condition I define it to be loaded. Each time I start _Vim_ it gets sourced without should be at this point. 

> It is not included in your minimal vimrcs and reproduce ways. Why?
Because one example that doesn't work seems to be enough. Else it would be multiple `.vimrc`'s, cause I tried to make it lazy loaded by different conditions. The crazy point is, that it works for other plugins already, but not here. For example I load `deoplete` on `InsertEnter` and it works as expected. I load `nerdtree_choosewin-plugin` `on_source` `nerdtree` and it works. ... But here no scenario works. _Vim-Devicons_ gets sourced and that's a problem. Cause then it does not register other plugins and so the symbiosis doesn't work.

**Comment by weilbith** [comment] 2018-06-11 07:56
Seems to be broken for in general for each new plugin currently.

**Closed** 2018-06-11 07:56 UTC
Labels: cannot understand

**Comment by Shougo** [comment] 2018-06-12 23:58
OK.

I cannot reproduce the problem.

**Comment by weilbith** [comment] 2018-06-13 09:02
I hope a new setup of my whole PC will solve this problem. 
All old lazy load definitions work. Every new I add doesn't work. I don't use the state, cause the problem of the hook functions (some issues earlier). I recached. I removed the whole ~/.cache/dein directory. I don't know what's wrong here.

**Comment by yusiwen** [comment] 2018-09-01 06:42
@Shougo @weilbith 
I've the same problem, plugin `Vim-Devicons` must be load after `NerdTree`, `Denite`, as they said in their official manual:

![image](https://user-images.githubusercontent.com/3704932/44943188-b7ad1800-adf4-11e8-8699-6c65f2830544.png)

But the problem is:

In my vimrc, NerdTree and Denite are both lazy loading when their commands are first called.

How can I load Vim-Devicons after them?

Thanks.

**Comment by Shougo** [comment] 2018-09-02 05:49
> In my vimrc, NerdTree and Denite are both lazy loading when their commands are called for the first time.

> How can I load Vim-Devicons after them?

Please use post_source for it.
