### ISSUE TITLE
How to load vim-devicons with denite when i lazyload them by dein

### ISSUE THREAD

**Issue by taigacute** [Shougo/dein.vim#342] opened 2019-06-07 12:53 UTC
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Hi，what  is the  correct order lazyload vim-devicons，denite？i use these plugins like lightline in dein.toml, startify denite defx in lazyload toml. now i can got the lightline startify ,defx works well with vim-devicons,but the denite cant work with vim-devicons.what should i do ?

## Expected
denite can work better with vim-devicons

## Environment Information (Required!)

 * dein.vim version(SHA1): the latest

 * OS: macos10.13.6

 * Vim/neovim version: neovim-0.4.0-dev

## Provide a minimal .vimrc with less than 50 lines (Required!)

```toml
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends='vim-devicons'
hook_source = '''
source ~/.config/nvim/core/plugins/denite.vim
source ~/.config/nvim/core/plugins/denite_menu.vim
'''
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add='''
let g:webdevicons_enable_denite = 1
'''

```

## The reproduce ways from Vim starting (Required!)

 1. use these settings in lazyload toml

## Screen shot (if possible)

N/A
## Upload the log messages by `:redir` and `:message` (if errored)
N/A

**Comment by Shougo** [comment] 2019-06-08 10:47
`depends = 'vim-devicons'` in denite.nvim should work.

Closing.

Because, you have not uploaded reproduce-able vimrc for other people.

You should check your is reproduce-able.

**Closed by Shougo** 2019-06-08 10:47 UTC

**Comment by Shougo** [comment] 2019-06-08 10:51
This is the real minimal reproduce-able vimrc.

```vim
set nocompatible
set runtimepath^=~/work/dein.vim

call dein#begin(expand('~/.cache/sample/dein'))

call dein#add('Shougo/denite.nvim', {'lazy': 1, 'depends': 'vim-devicons'})
call dein#add('ryanoasis/vim-devicons', {'lazy': 1})

let g:webdevicons_enable_denite = 1

call dein#end()

filetype plugin indent on
```

It works for me.

**Comment by taigacute** [comment] 2019-06-08 10:53
@Shougo ， I know this is a not real minal vimrc cause i split my vimrc  ,i will try it

**Comment by taigacute** [comment] 2019-06-08 11:18
@Shougo   Can you check this minal vimrc, i can use these vimrc reproduce problem
```Viml
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

call dein#add('Shougo/denite.nvim', {'lazy': 1, 'depends': 'vim-devicons','onCmd':'Denite','hook_source':'source ~/.config/nvim/core/plugins/denite.vim'})
call dein#add('ryanoasis/vim-devicons', {'lazy': 1,'hook_add':'let g:webdevicons_enable_denite = 1'})


  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

**Comment by Shougo** [comment] 2019-06-08 12:11
I don't work for it.

```vim
call dein#add('Shougo/denite.nvim', {'lazy': 1, 'depends': 'vim-devicons','onCmd':'Denite','hook_source':'source ~/.config/nvim/core/plugins/denite.vim'})
```

`onCmd` must be  `on_cmd`.
And you have not uploaded `source ~/.config/nvim/core/plugins/denite.vim`.

Please check `it must be reproduce-able for other people`.

**Comment by taigacute** [comment] 2019-06-08 12:30
@Shougo  sry ,  must be this
```VIML
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

call dein#add('Shougo/denite.nvim', {'lazy': 1, 'depends': 'vim-devicons','on_cmd':'Denite','hook_source':'source ~/.config/nvim/core/plugins/denite.vim'})
call dein#add('ryanoasis/vim-devicons', {'lazy': 1,'hook_add':'let g:webdevicons_enable_denite = 1'})


  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
```
my denite.vim
```
call denite#custom#option('_', {
		\ 'cached_filter': v:true,
		\ 'cursor_shape': v:true,
		\ 'cursor_wrap': v:true,
		\ 'highlight_filter_background': 'DeniteFilter',
		\ 'highlight_matched_char': 'Underlined',
		\ 'matchers': 'matcher/fruzzy',
		\ 'prompt': 'λ ',
		\ 'split': 'floating',
		\ 'start_filter': v:true,
		\ 'statusline': v:false,
		\ })
function! s:denite_detect_size() abort
    let s:denite_winheight = 20
    let s:denite_winrow = &lines > s:denite_winheight ? (&lines - s:denite_winheight) / 2 : 0
    let s:denite_winwidth = &columns > 240 ? &columns / 2 : 120
    let s:denite_wincol = &columns > s:denite_winwidth ? (&columns - s:denite_winwidth) / 2 : 0
    call denite#custom#option('_', {
          \ 'wincol': s:denite_wincol,
          \ 'winheight': s:denite_winheight,
          \ 'winrow': s:denite_winrow,
          \ 'winwidth': s:denite_winwidth,
          \ })
  endfunction
   augroup denite-detect-size
    autocmd!
    autocmd VimResized * call <SID>denite_detect_size()
  augroup END
  call s:denite_detect_size()


call denite#custom#option('search', { 'start_filter': 0, 'no_empty': 1 })
call denite#custom#option('list', { 'start_filter': 0 })
call denite#custom#option('jump', { 'start_filter': 0 })
call denite#custom#option('git', { 'start_filter': 0 })
call denite#custom#option('mpc', { 'winheight': 20 })

" MATCHERS
" Default is 'matcher/fuzzy'
call denite#custom#source('tag', 'matchers', ['matcher/substring'])
" call denite#custom#source('file/rec', 'matchers', ['matcher/fruzzy'])

if has('nvim') && &runtimepath =~# '\/cpsm'
	call denite#custom#source(
		\ 'buffer,file_mru,file_old,file/rec,grep,mpc,line,neoyank',
		\ 'matchers', ['matcher/cpsm', 'matcher/fuzzy'])
endif

" SORTERS
" Default is 'sorter/rank'
call denite#custom#source('z', 'sorters', ['sorter_z'])

" CONVERTERS
" Default is none
call denite#custom#source(
	\ 'buffer,file_mru,file_old',
	\ 'converters', ['converter_relative_word'])

" FIND and GREP COMMANDS
if executable('ag')
	" The Silver Searcher
	call denite#custom#var('file/rec', 'command',
		\ ['ag', '-U', '--hidden', '--follow', '--nocolor', '--nogroup', '-g', ''])

	" Setup ignore patterns in your .agignore file!
	" https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage

	call denite#custom#var('grep', 'command', ['ag'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('grep', 'separator', ['--'])
	call denite#custom#var('grep', 'final_opts', [])
	call denite#custom#var('grep', 'default_opts',
		\ [ '--skip-vcs-ignores', '--vimgrep', '--smart-case', '--hidden' ])

elseif executable('ack')
	" Ack command
	call denite#custom#var('grep', 'command', ['ack'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', ['--match'])
	call denite#custom#var('grep', 'separator', ['--'])
	call denite#custom#var('grep', 'final_opts', [])
	call denite#custom#var('grep', 'default_opts',
			\ ['--ackrc', $HOME.'/.config/ackrc', '-H',
			\ '--nopager', '--nocolor', '--nogroup', '--column'])

elseif executable('rg')
	" Ripgrep
  call denite#custom#var('file/rec', 'command',
        \ ['rg', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'default_opts',
        \ ['-i', '--vimgrep', '--no-heading'])
endif


" KEY MAPPINGS
autocmd FileType denite call s:denite_settings()
function! s:denite_settings() abort
	highlight! link CursorLine Visual
	nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
	nnoremap <silent><buffer><expr> i    denite#do_map('open_filter_buffer')
	nnoremap <silent><buffer><expr> d    denite#do_map('do_action', 'delete')
	nnoremap <silent><buffer><expr> p    denite#do_map('do_action', 'preview')
	nnoremap <silent><buffer><expr> st   denite#do_map('do_action', 'tabopen')
	nnoremap <silent><buffer><expr> sg   denite#do_map('do_action', 'vsplit')
	nnoremap <silent><buffer><expr> sv   denite#do_map('do_action', 'split')
	nnoremap <silent><buffer><expr> '    denite#do_map('quick_move')
	nnoremap <silent><buffer><expr> q    denite#do_map('quit')
	nnoremap <silent><buffer><expr> r    denite#do_map('redraw')
	nnoremap <silent><buffer><expr> yy   denite#do_map('do_action', 'yank')
	nnoremap <silent><buffer><expr> <Esc>   denite#do_map('quit')
	nnoremap <silent><buffer><expr> <C-u>   denite#do_map('restore_sources')
	nnoremap <silent><buffer><expr> <C-f>   denite#do_map('do_action', 'defx')
	nnoremap <silent><buffer><expr> <C-x>   denite#do_map('choose_action')
	nnoremap <silent><buffer><expr><nowait> <Space> denite#do_map('toggle_select').'j'
endfunction

autocmd FileType denite-filter call s:denite_filter_settings()
function! s:denite_filter_settings() abort
	nnoremap <silent><buffer><expr> <Esc>  denite#do_map('quit')
	" inoremap <silent><buffer><expr> <Esc>  denite#do_map('quit')
	nnoremap <silent><buffer><expr> q      denite#do_map('quit')
	imap <silent><buffer> <C-c> <Plug>(denite_filter_quit)
	"inoremap <silent><buffer><expr> <C-c>  denite#do_map('quit')
	nnoremap <silent><buffer><expr> <C-c>  denite#do_map('quit')
	inoremap <silent><buffer>       kk     <Esc><C-w>p
	nnoremap <silent><buffer>       kk     <C-w>p
	inoremap <silent><buffer>       jj     <Esc><C-w>p
	nnoremap <silent><buffer>       jj     <C-w>p
endfunction
```

**Comment by Shougo** [comment] 2019-06-08 12:33
OH.  it is too long.

It is not minimal.  Please reduce it as minimal.

And 

> defx works well with vim-devicons,but the denite cant work with vim-devicons.what should i do ?

Why do you think does not work?
Please describe it.  This is the reproduce instructions.
If you don't upload it, I don't work for the problem.

Please read other issues.  It is reproduce-able for your issue.

**Comment by Shougo** [comment] 2019-06-08 12:33
For example:

https://github.com/Shougo/dein.vim/issues/342#issuecomment-500114930

I have tested vim-devicons is loaded by `:scriptnames`.

**Comment by taigacute** [comment] 2019-06-08 12:42
denite.vim is my denite config, Does it affect vim-devicons?

**Comment by Shougo** [comment] 2019-06-08 12:44
Please test my minimal config before your config https://github.com/Shougo/dein.vim/issues/342#issuecomment-500114930.

I have tested `vim-devicons` is loaded.

**Comment by taigacute** [comment] 2019-06-08 12:45
i tested it doenst work.

**Comment by Shougo** [comment] 2019-06-08 12:45
I have required the minimal config to detect what is the problem.
It should work, because I have loaded.

I think the problem is from your config.

**Comment by Shougo** [comment] 2019-06-08 12:45
> i tested it doenst work.

What means the does not work?

**Comment by taigacute** [comment] 2019-06-08 12:48
@Shougo  maybe you can see this gif 
![nvim](https://user-images.githubusercontent.com/41671631/59147492-b9b0a100-8a2e-11e9-8a78-ab1797053331.gif)

**Comment by taigacute** [comment] 2019-06-08 12:53
@Shougo  i test  your config 
![nvim](https://user-images.githubusercontent.com/41671631/59147523-64c15a80-8a2f-11e9-8a3b-c2ebbdadd2f4.gif)

**Comment by Shougo** [comment] 2019-06-08 12:56
OK.  I get it.  It is bug of vim-devicons.

https://github.com/ryanoasis/vim-devicons/blob/master/autoload/devicons/plugins/denite.vim#L2

It must be:

```vim
call denite#custom#source('file/rec,file_mru,file/old,buffer,directory/rec,directory_mru', 'converters', ['devicons_denite_converter'])```

`:Denite buffer` works instead.

**Comment by Shougo** [comment] 2019-06-08 12:57
You can configure the converter manually in `~/.config/nvim/core/plugins/denite.vim`.

**Comment by taigacute** [comment] 2019-06-08 12:59
I got it， it works 。maybe can add this into the doc? what do you think ?

**Comment by Shougo** [comment] 2019-06-08 13:03
It should be fixed in vim-devicons's side.

**Comment by Shougo** [comment] 2019-06-08 13:04
`file_rec` and `file_old` are old names.
It is removed in the latest version.

**Comment by taigacute** [comment] 2019-06-08 13:06
> `file_rec` and `file_old` are old names.
> It is removed in the latest version.

thanks for your work . i will check it.
