### ISSUE TITLE
Compatibility with startuptime.vim

### ISSUE THREAD

**Issue by xelra** [Shougo/dein.vim#194] opened 2017-03-12 01:25 UTC
There's a new plugin called [startuptime.vim](https://github.com/tweekmonster/startuptime.vim), which is aiming to become an integrated diagnostic tool for Neovim (and Vim) to profile the startuptime of plugins.

Unfortunately it's not compatible with dein.vim, because of the paths that are used. 

I wanted to bring this to your attention and ask whether it's possible to make dein.vim compatible to startuptime.vim?

I've already asked on the other project, but unfortunately it's outside of the scope of startuptime.vim to support specific plugin managers.

**Comment by Shougo** [comment] 2017-03-12 01:26
I don't understand the problem.

**Comment by xelra** [comment] 2017-03-12 01:27
It's not a problem. It's a feature request.

https://github.com/tweekmonster/startuptime.vim/issues/3 details the issue between dein.vim and startuptime.vim.

**Comment by Shougo** [comment] 2017-03-12 01:28
Oh, the issue is too long...

**Comment by xelra** [comment] 2017-03-12 01:31
To summarize it:

startuptime.vim recognizes all plugins installed with dein.vim as `.dein` and cannot distinguish between the single plugins.

**Comment by Shougo** [comment] 2017-03-12 01:32
OK.  This is dein's feature.
You can disable the merging by `'merged':0`

**Closed by Shougo** 2017-03-12 01:32 UTC

**Comment by xelra** [comment] 2017-03-12 01:34
Thanks for the quick answer. How do I set `'merged': 0`? Where do I put it?

**Comment by Shougo** [comment] 2017-03-12 01:35
Please read the dein documentation.

**Comment by xelra** [comment] 2017-03-12 01:57
Thanks. I found it. It works well when set the `'merged': 0` option for every entry `dein#add` entry.

Is there an option to disable merging globally?

**Comment by Shougo** [comment] 2017-03-12 02:22
@xelra You can use `dein#load_toml()` or `dein#load_dict()`.
