### ISSUE TITLE
How does work dein#local() ?

### ISSUE THREAD

**Issue by hl037** [Shougo/dein.vim#329] opened 2019-02-19 02:55 UTC
How does `dein#local()` work ?

# Problems summary

I'm trying to develop a vim plugins. I read in the documentation that `dein#local` permits to have a folder where all plugins in it will be installed. But is there any structure I should respect ?

For example : I tried to do a "hl037report" plugin. My files looks like this : 

```
~/
  .vim/
    dein/
      ...
    me/
      hl037report/
        plugin/
          hl037report.vim
        ftdetect/
          hl037report.vim
        ftplugin/
          hl037report.vim
        syntax/
          hl037report.vim
```

I tried to put that on my vimrc : 

```
" Required:
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.vim/dein/')
   call dein#begin('~/.vim/dein/')

   " Let dein manage dein
   " Required:
   call dein#add('~/.vim/dein/repos/github.com/Shougo/dein.vim')
   
   call dein#local('~/.vim/me/')
endif
```

...But the plugin is not loaded. 

# What I tried :

- I tried with the frozen option as specified here : https://github.com/Shougo/dein.vim/issues/4
- I tried `dein#add('~/.vim/me/hl037report')`
- I tried `dein#local('~/.vim/me/hl037report')`
- I tried both these command with `frozen` option.
- delete cache
- reinstall from scratch

# What I get : 

The plugin is never loaded (same in vim and neovim)

If I call `dein#update()` it updates all my previously installed
If I call `dein#install()` I get the "[dein] Target plugins are not found." message (no matter if I add or remove the plugin line from the vimrc)

If I call `dein#install()` for the first time (reinstalled from scratch), it installs all the plugins, but totally ignores the dein#local() call

Any idea ?

Either it is a bug, either I am doing something wrong, and you may add some details to the documentation because there are no ressources on how it is meant to be used...

**Comment by Shougo** [comment] 2019-02-19 23:37
You don't upload the example plugin.  It cannot be tested for other people.

And you don't describe what is the `But the plugin is not loaded.`.
We have not ESP skills.

It is not bug.
I have tested `dein#local()` behavior.  It works expected.
I don't work for non-reproduce-able issues.
Closing.

> Either it is a bug, either I am doing something wrong, and you may add some details to the documentation because there are no ressources on how it is meant to be used...

You can improve the documentation.  It is OSS.

**Closed by Shougo** 2019-02-19 23:37 UTC

**Comment by hl037** [comment] 2019-02-20 13:05
I didn't upload it because it is a simple `echom` script, that is not loaded.
I though "but the plugin is not loaded" pretty clear as stating "the plugin scripts don't appears in the `:scriptnames` output" (at least the `plugin/hl037report.vim` and the `ftdetect/hl037report.vim` ones should have been listed)

Yes I can improve the documentation myself. But first, I need to understand how it works (since I've never been able to add local plugins with dein... neither using `dein#add` neither using `dein#local`)

This issue was not about a bug (else I would have chosen another title) but about "How am I supposed to use `dein#local` ?" with an example. Admit at least the resources on it are quite limited and not straightforward. (when I choose a plugin manager, it's not to look inside its source, it's because it's easy and straightforward to use)

I switched to vim-plug and everything worked fine at first try... (While I struggled for days with dein). That makes me reconsider the "not a bug" part.

If you are willing to dig more on this question/issue, I will be happy to help by providing the informations you need, but if not, I admit I won't since I am good with vim-plug...

**Comment by Shougo** [comment] 2019-02-21 07:56
> I didn't upload it because it is a simple `echom` script, that is not loaded.
I though "but the plugin is not loaded" was pretty clear as stating "the plugin scripts don't appears in the `:scriptnames` output" (at least the `plugin/hl037report.vim` and the `ftdetect/hl037report.vim` ones should have been listed)

It may be simple script.  But you must upload it.
Because I cannot test your plugin.

If you upload it, I will create the minimal vimrc and test it.

Until done, I don't rework for the issue.

`dein#local()` adds the plugins in the directory.
For example, `dein#local('~/work')` adds `~/work/*` plugins.

**Comment by Shougo** [comment] 2019-02-21 07:57
> I switched to vim-plug and everything worked fine at first try... (While I struggled for days with dein). That makes me reconsider the "not a bug" part.

vim-plug has not `dein#local()` feature.
