### ISSUE TITLE
Weird behavior of delimitmate when loaded with on_map: [['i', '(']]

### ISSUE THREAD

**Issue by gbcreation** [Shougo/dein.vim#91] opened 2016-05-02 07:15 UTC
# Problems summary

With the minimal .vimrc given below, when i hit the `(` key for the first time, the `(` character is inserted before the cursor.

For example, starting with (`|` is the cursor):
```
test|
```
After hitting the `(`key, I get:
```
tes(|t
```

If I replay this scenario a second time, it works as expected.

## Expected
The `(` character should be inserted at the cursor position and automatically closed by delimitmate:
```
test(|)
```

## Environment Information
 * OS: ArchLinux
 * Vim version: Neovim 0.1.4

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
let g:loaded_matchparen = 1
let s:plugins_dir = expand('~/.cache/nvim/dein-test')
let s:dein_plugin_dir = s:plugins_dir . '/repos/github.com/shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_plugin_dir)
        if executable('git')
            execute '!git clone https://github.com/shougo/dein.vim' s:dein_plugin_dir
        else
            echohl WarningMsg | echom "Git must be installed for Dein to work" | echohl None
            finish
        endif
    endif
    execute 'set runtimepath^=' . substitute( fnamemodify(s:dein_plugin_dir, ':p'), '/$', '', '')
endif

if dein#load_state(s:plugins_dir)
    call dein#begin(s:plugins_dir, [expand('<sfile>')])
    call dein#add('shougo/dein.vim')
    call dein#add('Raimondi/delimitMate', {
    \    'on_map': [['i', '(']],
    \ })
    call dein#end()
endif

call dein#save_state()

if !has('vim_starting') && dein#check_install()
    call dein#install()
endif

filetype on
```

## The reproduce ways from Vim starting (Required!)

 1. Launch `nvim`
 2. Enter insertion mode and write some text
 3. Hit the `(` key

**Comment by Shougo** [comment] 2016-05-03 03:42
Reproduced.  But I cannot reproduce it in Vim 7.4.1786.
So, it seems `feedkeys()` bug which is already fixed in Vim.

You should use `'on_event': 'InsertCharPre'` or `'on_event': 'InsertEnter'`

**Closed by Shougo** 2016-05-03 03:42 UTC
Labels: cannot fix, neovim

**Comment by gbcreation** [comment] 2016-05-04 07:09
Thank you for your investigation.
To make it works with `'on_event': 'InsertCharPre'`, I have to use this configuration:
```vim
call dein#add('Raimondi/delimitMate', {
    \    'on_event':    'InsertCharPre',
    \    'on_if':       'index(["(", "{"], v:char) != -1',
    \    'hook_source': 'call feedkeys(v:char) | let v:char = ""',
    \ })
```
When I initially hit the `(` key, it loads the delimitmate plugin, but the delimitmate mapping for this key is not executed. It is necessary to queue this key again using `call feedkeys(v:char)`so that the delimitmate mapping, which is now defined, is executed. `let v:char = ""`is required to avoid the insertion of the initial `(` character by the `InsertCharPre`event.

**Comment by Shougo** [comment] 2016-05-07 02:04
@gbcreation I have supported it.
You don't have to hack `feedkeys()`.

**Comment by gbcreation** [comment] 2016-05-07 09:50
It works perfectly, thank you.
The configuration is now:
```vim
call dein#add('Raimondi/delimitMate', {
    \    'on_event':    'InsertCharPre',
    \    'on_if':       'index(["(", "{"], v:char) != -1'
    \ })
```
