### ISSUE TITLE
Installing git submodules

### ISSUE THREAD

**Issue by petobens** [Shougo/dein.vim#113] opened 2016-06-29 19:21 UTC
When adding the following plugin

```vim
call dein#add('tweekmonster/impsort.vim', {'rev': 'import-types',
            \ 'on_ft' : 'python'})
```

the jedi submodule was not installed. I expect `dein` to install git submodules.
[Reference](https://github.com/tweekmonster/impsort.vim/issues/4#issuecomment-229454859)

**Comment by Shougo** [comment] 2016-06-30 22:57
I cannot reproduce it.
And it seems not dein.vim problem.
I have read the proposed issue.
(Why don't you close it?)

Closing.

**Closed by Shougo** 2016-06-30 22:57 UTC
