### ISSUE TITLE
cleaning unused plugins with dein#check_clean() not working as expected

### ISSUE THREAD

**Issue by yedhink** [Shougo/dein.vim#292] opened 2018-06-09 07:01 UTC
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
i removed a plugin a plugin add line from my "init.vim" of neovim and wanted to clean the unused directory from the repos. what i did was the following:  

- Remove the dein#add() lines

- call dein#recache_runtimepath()

- call map(dein#check_clean(), "delete(v:val, 'rf')")

but after doing so, it didn't remove the unwanted/unused plugins, but rather it removed 'Shougo/dein.vim' from my runtimepath and i had to reinstall dein  

## Expected
i expected the above commands to remove plugins (only the ones that i removed from my neovim config) like 'PlugClean' command of vim-plug would have done, which i had previously used. 

## Environment Information (Required!)

 * dein.vim version(SHA1):065f3f2421350782ffc850d0e37b2dc2885c51a5

 * OS: Arch Linux( 4.16.13-2-ARCH)

 * Vim/neovim version:NVIM v0.3.0-1304-gf711b6351

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
" Your minimal .vimrc
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('~/.cache/dein')
     .
     .
     .
    call dein#end()
    call dein#save_state()
endif
```

## The reproduce ways from Vim starting (Required!)

 1. open nvim
 2. remove unnecessary plugin line
 3. call dein#recache_runtimepath()
 4. call map(dein#check_clean(), "delete(v:val, 'rf')")
 5. reopen neovim

## Upload the log messages by `:redir` and `:message` (if errored)
No errors or anything

**Comment by Shougo** [comment] 2018-06-09 07:04
Please upload the real minimal vimrc.
If not, I will close the issue.

**Comment by Shougo** [comment] 2018-06-09 07:05
And it is invalid.

```vim
call dein#add('~/.cache/dein')
```

**Comment by yedhink** [comment] 2018-06-09 07:09
if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('~/.cache/dein')
    call dein#add('ajmwagar/vim-deus')   
    call dein#add('zchee/deoplete-jedi')                                                                                                               " python completion
    call dein#add('Shougo/deoplete.nvim')                                                                                                              " dark powered completions \m/
    call dein#add('Shougo/neosnippet.vim')                                                                                                             " snippets
    call dein#add('Shougo/neosnippet-snippets')                                                                                                        " whole collection
    call dein#add('Shougo/denite.nvim')                                                                                                                
    call dein#end()
    call dein#save_state()
endif
" dein config
let g:dein#install_max_processes = 16
let g:dein#install_progress_type = 'echo'
let g:dein#enable_notification = 0
filetype plugin on
filetype indent on
" Set split direction
set splitbelow
set splitright

" Set updatetime
set updatetime=2000

**Comment by Shougo** [comment] 2018-06-09 07:11
It is broken.

It must be:

```vim
if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('ajmwagar/vim-deus')   
    call dein#add('zchee/deoplete-jedi')                                                                                                               " python completion
    call dein#add('Shougo/deoplete.nvim')                                                                                                              " dark powered completions \m/
    call dein#add('Shougo/neosnippet.vim')                                                                                                             " snippets
    call dein#add('Shougo/neosnippet-snippets')                                                                                                        " whole collection
    call dein#add('Shougo/denite.nvim')                                                                                                                
    call dein#end()
    call dein#save_state()
endif
```

**Closed** 2018-06-09 07:11 UTC
Labels: cannot reproduce, needs reproduction instructions

**Comment by Shougo** [comment] 2018-06-09 07:13
You should check `dein#check_clean()` result.

**Comment by Shougo** [comment] 2018-06-09 07:13
`dein#check_clean()` works for me.
I have tested.

**Comment by yedhink** [comment] 2018-06-09 07:16
sir i ran that first in vim command line. but nothing happened. that's why i ran the above commands which removed `Shougo/dein.vim`.  and i dont understand what's the difference between the minimal vimrc configuration that i produced and the changes you suggested. both look the same to me

**Comment by Shougo** [comment] 2018-06-09 07:17
I have tested.

```vim
set runtimepath^=~/work/dein.vim/

call dein#begin('~/test/dein4')
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/deoplete.nvim')
call dein#add('Shougo/denite.nvim')
call dein#add('Shougo/defx.nvim')
call dein#end()
```

It works for me.

**Comment by Shougo** [comment] 2018-06-09 07:20
> but after doing so, it didn't remove the unwanted/unused plugins, but rather it removed 'Shougo/dein.vim' from my runtimepath and i had to reinstall dein

I think you have removed `dein.vim` line.

**Comment by Shougo** [comment] 2018-06-09 07:27
`dein#check_clean()` just returns list.
So `call` is no meaning.

**Comment by yedhink** [comment] 2018-06-09 07:28
tried `echo dein#check_clean()`......it gives back empty [] list and i did try `call map(dein#check_clean(), "delete(v:val, 'rf')")`...nothing happening

**Comment by Shougo** [comment] 2018-06-09 07:29
https://github.com/Shougo/dein.vim/issues/292#issuecomment-395947065

Have you tested the example?
It works for me.

**Comment by Shougo** [comment] 2018-06-09 07:30
You need to call `dein#recache_runtimepath()` if you use cache feature.

**Comment by Shougo** [comment] 2018-06-09 07:30
I cannot reproduce the problem.

**Comment by yedhink** [comment] 2018-06-09 07:32
it's solved now. thanks!

**Comment by michaelcusick** [comment] 2020-11-24 14:46
@Shougo this issue can be closed now.

**Comment by Shougo** [comment] 2020-11-25 01:30
It is already closed.
