### ISSUE TITLE
Why loaded ALE? (Lazy-load Not Working)

### ISSUE THREAD

**Issue by takxlz** [Shougo/dein.vim#305] opened 2018-08-08 05:42 UTC
# Problems summary
ALEにon_ftによるlazy-load設定をしても，設定したファイルタイプに関係なく以下のタイミングでロードされてしまう．

Vim: BufReadのタイミングでロードされる．
Neovim: VimEnterのタイミングでロードされる．

## Environment Information (Required!)
- Windows10
- Vim8.1, Neovim0.3.1
- dein.vim latest

## Provide a minimal .vimrc with less than 50 lines (Required!)
```vim
[[plugins]]
repo = 'w0rp/ale'
on_ft = 'javascript'
```

## The reproduce ways from Vim starting (Required!)
**In the case of Vim**
 1. :echo dein#is_sourced('ale') => 0
 2. [BufRead]  (not javascript file)
 3. :echo dein#is_sourced('ale') => 1

**In the case of Neovim**
 1. :echo dein#is_sourced('ale') => 1

**Comment by Shougo** [comment] 2018-08-10 00:31
Please test the minimal .vimrc.
I cannot reproduce the problem in the minimal .vimrc.

Closing.

**Closed by Shougo** 2018-08-10 00:31 UTC

**Comment by takxlz** [comment] 2018-08-10 04:52
thank you.
I checked the my vimrc.
It was caused by lightline.vim(not lazy) calling ALE function.
