### ISSUE TITLE
dein#remote_plugin doesnt work

### ISSUE THREAD

**Issue by taigacute** [Shougo/dein.vim#344] opened 2019-06-18 05:31 UTC
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
i used `dein#install()`, but when denite installed ,i call denite by command `Denite file/rec`, I got error call me use `:UpdateRemotePlugins`, if ` dein#install()` call the `dein#remote_plugins`,i should not got this right?

## Environment Information (Required!)

 * dein.vim version(SHA1):the latest version

 * OS:linux 

 * Vim/neovim version:NVIM v0.4.0-1056-g494675190

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('Shougo/denite.nvim', {'lazy': 1, 'on_cmd':'Denite'})

  call dein#end()
  call dein#save_state()
  if dein#check_install()
     call dein#install()
  endif
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from Vim starting (Required!)
 i create a manjaro linux. then `pip3 install  pynvim`
 1. use this minal vimrc
 2. when denite installed 
 3. `:Denite file/rec`

## Screen shot (if possible)
![ranger](https://user-images.githubusercontent.com/41671631/59655521-32e98a00-91cd-11e9-9da8-7a99d076489c.gif)

**Comment by zgpio** [comment] 2019-06-18 06:02
I can't reproduce your problem. It works for me.

**Comment by Shougo** [comment] 2019-06-18 14:17
I have tested your minimal vimrc and it works for me like @zgpio .

I think you have executed `:UpdateRemoteplugins` manually.
You should not.

Because, denite.nvim is lazy plugin and it is not loaded when executing `:UpdateRemotePlugins`.

**Comment by Shougo** [comment] 2019-06-18 14:17
If other people reproducible the problem with the minimal vimrc, I will re-open it.

**Comment by Shougo** [comment] 2019-06-18 14:19
You need to call `dein#remote_plugins()` manually to fix the problem.

**Comment by taigacute** [comment] 2019-06-18 14:20
@Shougo   i didnt have executed `:UpdateRemotePlugins`, this gif.  i set the init.vim then open the nvim, it exec `call dein#install()`  to installed the Denite. when intalled success . i open the nvim and run command

**Comment by taigacute** [comment] 2019-06-18 14:23
if `dein#install()` call the `dein#remote`, nomatter the plugin lazyload or not lazload. always do `remote`? i remember you said to me the `dein#install()` will auto call `dein#remote` , it only for not lazyload plugins? right?

**Comment by Shougo** [comment] 2019-06-18 14:30
Really?  It should work.

Please read the source code.

`dein#remote_plugins()` is called in `dein#install#_recache_runtimepath()`.

Hm.

In first, please use `call dein#recache_runtimepath()`.
It fixes your problem?

**Comment by Shougo** [comment] 2019-06-18 14:32
`dein#install#_recache_runtimepath()` is called in `s:done()`.
You can read the source code.

And you have the source code and reproducible environment.
You can research the problem.

If it is dein's bug, I will fix it.

**Comment by Shougo** [comment] 2019-06-18 14:34
* Please check `call dein#recache_runtimepath()` fixes the problem.
* Please re-install `denite.nvim` and reproducible the problem.

**Comment by Shougo** [comment] 2019-06-18 14:36
To reinstall denite.nvim:

`call dein#reinstall('denite.nvim')`

**Comment by taigacute** [comment] 2019-06-18 14:38
i will made a new gif .this gif will show you this env

**Comment by Shougo** [comment] 2019-06-18 14:39
>  i didnt have executed :UpdateRemotePlugins, this gif. i set the init.vim then open the nvim, it exec call dein#install() to installed the Denite. 

I have not see `call dein#install()` in the gif.

**Comment by Shougo** [comment] 2019-06-18 14:43
Or you can remove dein directory and reinstall plugins.
Please check `dein#install#_recache_runtimepath()` is called after installed.

**Comment by Shougo** [comment] 2019-06-18 14:44
I think you are not Vim beginner.  So you can research the problem.
I wait your report.

**Comment by taigacute** [comment] 2019-06-18 14:50
but i saw the log. didnt see any useful information . may be need check the code.

**Comment by taigacute** [comment] 2019-06-18 14:51
I have a solution to this problem. Just wondering what happened

**Comment by taigacute** [comment] 2019-06-18 14:55
![Untitled](https://user-images.githubusercontent.com/41671631/59694995-10329200-921c-11e9-9026-4709283f22c8.gif)

**Comment by Shougo** [comment] 2019-06-18 15:12
Please answer my questions.
And please check the code.

**Comment by Shougo** [comment] 2019-06-18 15:15
I think it is easy to debug.
Why?
Because you can reproduce the problem easily and you have the source code and the author is here.

**Comment by taigacute** [comment] 2019-06-18 15:21
i try to use  the `dein#remote_plugins()`  and `dein#install#_recache_runtimepath()`  ,then remove the dein folder. and reinstall the plugins .didnt work.  Whether it is related to the way I install dein by git clone not use `sh ./installer.sh` ?

**Comment by taigacute** [comment] 2019-06-18 15:27
@Shougo   thanks for your work!!!  its  `1am`  in japan ,maybe you need rest. 
I think what I messed up, if it is a problem with dein, it won’t be discovered until now.

**Comment by Shougo** [comment] 2019-06-18 23:32
> i try to use the dein#remote_plugins() and dein#install#_recache_runtimepath() ,then remove the dein folder. and reinstall the plugins .didnt work.

Please test `call dein#recache_runtimepath()` after `Denite file/rec`.

1. `:Denite file/rec` -> It will be error in your environment
2. restart Vim
3. `:call dein#recache_runtimepath()` manually.
4. restart Vim
5. `Denite file/rec` -> It should work.

**Comment by Shougo** [comment] 2019-06-18 23:36
And please save/upload the log file after `dein#install()`.

If you set `g:dein#install_log_filename`, the log is saved to the file.

**Comment by Shougo** [comment] 2019-06-18 23:44
I have added the logging in dein.vim.
Please use the latest version of dein.vim and test https://github.com/Shougo/dein.vim/issues/344#issuecomment-503350203.

**Comment by Shougo** [comment] 2019-06-18 23:46
I will test the log file, but if you don't test/upload the log file.
I will close the issue again.

**Comment by Shougo** [comment] 2019-06-19 01:43
Reproduced.
I will fix it later.

**Comment by taigacute** [comment] 2019-06-19 01:59
@Shougo  thanks.!

**Comment by Shougo** [comment] 2019-06-19 12:33
Fixed.

**Closed** 2019-06-19 12:32 UTC
Labels: cannot reproduce

**Comment by taigacute** [comment] 2019-06-19 12:42
fixed! thanks !
